// Command skillsync mirrors the skills in .claude/skills to every other agent's
// conventions, so one set of instructions serves all of them.
//
//	make skills         # write the mirror and the AGENTS.md index
//	make skills-check   # fail if either is out of date (CI runs this)
//
// The skills themselves are agent-neutral already: a SKILL.md is a markdown file
// with a `name` and a `description`, and nothing in ours is Claude-specific.
// What is not neutral is *where* an agent looks. Claude Code reads
// .claude/skills; Codex reads .codex/skills and has no setting that would point
// it elsewhere. Copying the prose into both is how the two would start
// disagreeing, so .codex/skills gets a generated stub instead: the frontmatter,
// which is the whole discovery contract, and one line telling the agent which
// file to open. The skill is written once and reviewed once.
//
// The same reasoning covers the index in AGENTS.md, which is what an agent with
// no skill mechanism at all reads: it is the descriptions again, so it is
// generated from them rather than kept in step by hand.
//
// It writes nothing outside .codex/skills and the marked block in AGENTS.md.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	// canonicalDir holds the real skills — the ones a human writes and reviews.
	canonicalDir = ".claude/skills"
	// mirrorDir is generated from it, one stub per skill.
	mirrorDir = ".codex/skills"
	// agentsFile carries the index, between the two markers below.
	agentsFile = "AGENTS.md"

	startMarker = "<!-- skills:start -->"
	endMarker   = "<!-- skills:end -->"

	// generatedLine appears in every stub. It is what lets this tool tell a
	// directory it wrote from one somebody else put there, so removing a stub
	// whose skill is gone can never delete a hand-written file.
	generatedLine = "<!-- generated by `make skills` from " + canonicalDir + " — do not edit -->"
)

func main() {
	check := flag.Bool("check", false, "report what is out of date and exit non-zero, writing nothing")
	flag.Parse()

	if err := run(*check); err != nil {
		fmt.Fprintln(os.Stderr, "skillsync:", err)
		os.Exit(1)
	}
}

func run(check bool) error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	skills, err := readSkills(filepath.Join(root, filepath.FromSlash(canonicalDir)))
	if err != nil {
		return err
	}
	if len(skills) == 0 {
		return fmt.Errorf("no skills found in %s", canonicalDir)
	}

	// stale collects every difference rather than stopping at the first, so one
	// run tells you everything `make skills` would change.
	var stale []string

	for _, s := range skills {
		path := filepath.Join(root, filepath.FromSlash(mirrorDir), s.name, "SKILL.md")
		changed, err := reconcile(path, s.stub(), check)
		if err != nil {
			return err
		}
		if changed {
			stale = append(stale, rel(root, path))
		}
	}

	orphans, err := orphanStubs(filepath.Join(root, filepath.FromSlash(mirrorDir)), skills)
	if err != nil {
		return err
	}
	for _, dir := range orphans {
		if check {
			stale = append(stale, rel(root, dir)+" (no such skill any more)")
			continue
		}
		if err := os.RemoveAll(dir); err != nil {
			return err
		}
		fmt.Println("removed", rel(root, dir))
	}

	indexPath := filepath.Join(root, agentsFile)
	changed, err := reconcileIndex(indexPath, skills, check)
	if err != nil {
		return err
	}
	if changed {
		stale = append(stale, agentsFile+" (skills index)")
	}

	if !check {
		fmt.Printf("skillsync: %d skills mirrored to %s and indexed in %s\n", len(skills), mirrorDir, agentsFile)
		return nil
	}

	if len(stale) > 0 {
		return fmt.Errorf("out of date:\n  %s\nrun `make skills` and commit the result",
			strings.Join(stale, "\n  "))
	}

	fmt.Printf("skillsync: %s and %s are up to date\n", mirrorDir, agentsFile)

	return nil
}

// skill is one directory under .claude/skills, reduced to what the mirror and
// the index need: the two frontmatter fields.
type skill struct {
	name        string
	description string
}

// stub is what an agent that discovers skills by directory finds. It carries the
// frontmatter — which is what the discovery matches on, so it has to be the real
// text — and then hands over rather than repeating the skill.
func (s skill) stub() string {
	return fmt.Sprintf(`---
name: %s
description: %s
---

# %s

%s

**This is a pointer, not the skill.** The skill is
[%s/%s/SKILL.md](../../../%s/%s/SKILL.md) — read that file now and follow it.
It is the same instructions Claude Code loads; this copy exists only because
each agent looks for skills in its own directory.
`, s.name, s.description, s.name, generatedLine, canonicalDir, s.name, canonicalDir, s.name)
}

// readSkills reads every skill directory, in the order the filesystem lists them
// — which is sorted, so the index is stable between runs.
func readSkills(dir string) ([]skill, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	skills := make([]skill, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue // README.md, which is the index for humans
		}

		path := filepath.Join(dir, e.Name(), "SKILL.md")
		raw, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			continue // a directory that is not a skill is not ours to police
		}
		if err != nil {
			return nil, err
		}

		s, err := parse(string(raw))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		// The name is what every agent addresses the skill by, and the
		// directory is what it finds it in. They disagreeing is a mistake in
		// the skill, not something to mirror faithfully.
		if s.name != e.Name() {
			return nil, fmt.Errorf("%s: frontmatter name %q does not match its directory %q", path, s.name, e.Name())
		}

		skills = append(skills, s)
	}

	return skills, nil
}

// parse reads the YAML frontmatter without a YAML parser: the two fields are
// single-line scalars by convention, and a dependency to read them would be a
// dependency the whole repository then carries.
func parse(content string) (skill, error) {
	// TrimPrefix drops a UTF-8 byte order mark, which an editor on Windows can
	// leave at the front of the file and which would hide the --- below it.
	rest, ok := strings.CutPrefix(strings.TrimPrefix(content, "\xef\xbb\xbf"), "---\n")
	if !ok {
		return skill{}, errors.New("no frontmatter: the file must start with ---")
	}

	block, _, ok := strings.Cut(rest, "\n---")
	if !ok {
		return skill{}, errors.New("frontmatter is not closed with ---")
	}

	var s skill
	for line := range strings.SplitSeq(block, "\n") {
		key, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}

		// The description itself contains colons, so only the first one
		// separates the key: everything after it is the value.
		switch strings.TrimSpace(key) {
		case "name":
			s.name = strings.TrimSpace(value)
		case "description":
			s.description = strings.TrimSpace(value)
		}
	}

	switch {
	case s.name == "":
		return skill{}, errors.New("frontmatter has no name")
	case s.description == "":
		return skill{}, errors.New("frontmatter has no description")
	case strings.Contains(s.description, "|"):
		// It would break the markdown table in AGENTS.md, and the fix belongs
		// in the description rather than in an escaping rule nobody can see.
		return skill{}, errors.New("description contains a | , which the AGENTS.md index cannot hold")
	}

	return s, nil
}

// reconcile writes content to path, or reports whether writing it would change
// anything. It returns true when the file was stale.
func reconcile(path, content string, check bool) (bool, error) {
	current, err := os.ReadFile(path)
	switch {
	case err == nil && string(current) == content:
		return false, nil
	case err != nil && !errors.Is(err, os.ErrNotExist):
		return false, err
	}

	if check {
		return true, nil
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, err
	}

	fmt.Println("wrote", path)

	return true, nil
}

// reconcileIndex rewrites the block between the two markers in AGENTS.md.
//
// Only that block: the file around it is written by hand, and a tool that
// rewrote the whole file would make it unwritable.
func reconcileIndex(path string, skills []skill, check bool) (bool, error) {
	current, err := os.ReadFile(path)
	if err != nil {
		return false, fmt.Errorf("%s: %w (it holds the skills index between the %s markers)", path, err, startMarker)
	}

	before, rest, ok := strings.Cut(string(current), startMarker)
	if !ok {
		return false, fmt.Errorf("%s: no %s marker", path, startMarker)
	}
	_, after, ok := strings.Cut(rest, endMarker)
	if !ok {
		return false, fmt.Errorf("%s: no %s marker", path, endMarker)
	}

	var table bytes.Buffer
	table.WriteString(startMarker)
	table.WriteString("\n\n| Skill | What it covers, and when to read it |\n|---|---|\n")
	for _, s := range skills {
		fmt.Fprintf(&table, "| [`%s`](%s/%s/SKILL.md) | %s |\n", s.name, canonicalDir, s.name, s.description)
	}
	table.WriteString("\n")
	table.WriteString(endMarker)

	updated := before + table.String() + after
	if updated == string(current) {
		return false, nil
	}

	if check {
		return true, nil
	}

	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		return false, err
	}

	fmt.Println("wrote", path)

	return true, nil
}

// orphanStubs finds mirrored skills that no longer exist upstream — a renamed or
// deleted skill would otherwise keep answering from the mirror. Only directories
// this tool wrote are returned, which is what generatedLine is for.
func orphanStubs(dir string, skills []skill) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	known := make(map[string]bool, len(skills))
	for _, s := range skills {
		known[s.name] = true
	}

	var orphans []string
	for _, e := range entries {
		if !e.IsDir() || known[e.Name()] {
			continue
		}

		content, err := os.ReadFile(filepath.Join(dir, e.Name(), "SKILL.md"))
		if err != nil || !strings.Contains(string(content), generatedLine) {
			continue // not ours
		}

		orphans = append(orphans, filepath.Join(dir, e.Name()))
	}

	return orphans, nil
}

// repoRoot walks up from the working directory to the go.mod, so the tool works
// from a subdirectory and from an editor's run button, not only from `make`.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("no go.mod above the working directory: run this from inside the repository")
		}
		dir = parent
	}
}

func rel(root, path string) string {
	if r, err := filepath.Rel(root, path); err == nil {
		return filepath.ToSlash(r)
	}

	return path
}
